name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  # Cancel previous actions from the same PR: https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        bazelversion: [7.*, 8.*, 9.*, last_green]
        folder: [examples]
        include:
          - os: ubuntu-latest
            bazelversion: 9.*
            folder: "."

    steps:
      - uses: actions/checkout@v5

      - name: Configure Bazel version
        working-directory: ${{ matrix.folder }}
        run: echo "${{ matrix.bazelversion }}" > .bazelversion

      - name: Install and add ASAN runtime DLL to PATH on Windows
        if: matrix.os == 'windows-latest' && matrix.folder == 'examples'
        run: |
          $vsWherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $visualStudioInstallPath = & $vsWherePath -latest -products * -property installationPath
          if (-not $visualStudioInstallPath) {
            throw "Unable to determine Visual Studio installation path."
          }

          Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList "modify --installPath `"$visualStudioInstallPath`" --quiet --add Microsoft.VisualStudio.Component.VC.ASAN" -Wait -PassThru

          $msvcToolsDir = Join-Path $visualStudioInstallPath "VC\Tools\MSVC"
          $latestMsvcDir = Get-ChildItem $msvcToolsDir -Directory | Sort-Object Name -Descending | Select-Object -First 1
          if (-not $latestMsvcDir) {
            throw "Unable to locate MSVC tools in '$msvcToolsDir'."
          }

          $msvcBinDir = Join-Path $latestMsvcDir.FullName "bin\Hostx64\x64"
          if (-not (Test-Path $msvcBinDir)) {
            throw "Unable to locate MSVC binaries in '$msvcBinDir'."
          }
          $msvcBinDir | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: bazel test //...
        working-directory: ${{ matrix.folder }}
        shell: bash
        run: bazel test --config=ci //...

      - name: bazel coverage //...
        if: matrix.os == 'ubuntu-latest' && matrix.folder == 'examples'
        working-directory: ${{ matrix.folder }}
        run: bazel coverage --config=ci //...
